### ISSUE TITLE
Cosine Similarity Approximation

### ISSUE THREAD

**Issue by danielfleischer** [WICG/floc#128]
Hi, a bit off topic but I was curious. Using the PrefixLSH, I see it as a deterministic SimHash, where projections are not random but based on Cartesian unit vectors; I was wondering whether the probability behavior (roughly cosine per bit, exponential decay for larger number of bits) is maintained regarding cluster membership (before the prefix sorting). Thanks!

**Comment by michaelkleber** [comment]
Hi @danielfleischer: The randomness happens because we start with a pseudorandom map from 64-bit-hash(domain name) to a 50-dimensional space.  You can think of the [SimHashWeightedFeatures()](https://source.chromium.org/chromium/chromium/src/+/master:components/federated_learning/sim_hash.cc;l=54) step as a pseudorandom projection from a space of dimension 2^64 to a space of dimension 50, and then we take Cartesian unit vector slices in that 50-dim space.

**Comment by danielfleischer** [comment]
Thanks for pointing out the domain embeddings as the source for randomness and also linking the actual chrome implementation, that's useful.
