### ISSUE TITLE
Floc numbers and creation

### ISSUE THREAD

**Issue by iab-france** [WICG/floc#35]
Hello everyone,

Following the initial PoC phase and whitepaper that Google went through, do we now have a clearer idea of the number of FLOC we should expect as well as their expected size?
Also, will FLOC be common across browsers, or will they be unique per browsers? In the second case, does it means that DSP and other tech provider optimizing toward FLOC will need to optimize toward FLOC / UA couple rather than FLOC alone?

**Comment by michaelkleber** [comment]
Hello @iab-france,

> Following the initial PoC phase and whitepaper that Google went through, do we now have a clearer idea of the number of FLOC we should expect as well as their expected size?

Our intent is to ensure that each flock contains thousands of people.  Initially, the only way we have to make that kind of guarantee is by looking at [a subset of people using Chrome Sync](https://github.com/WICG/floc#qualifying-users-for-whom-a-cohort-will-be-logged-with-their-sync-data), since for people outside that subset, we don't have any special way to learn what flock they're in.  So we'll start by forcing at least 1000 people in each flock in our syncing subset, and then we (and everyone else!) can measure how many people with each flock we see.

> Also, will FLOC be common across browsers, or will they be unique per browsers? In the second case, does it means that DSP and other tech provider optimizing toward FLOC will need to optimize toward FLOC / UA couple rather than FLOC alone?

The flock API will return both the user's assigned flock _and_ a string indicating what flock clustering model was used to create it.  Any non-Chrome browser that decided to experiment with flocks would then need to decide whether they wanted to re-use the Chrome clustering technique, or wanted to try their own clustering approach.  Any consumer of flocks would want to use the reported clustering model to tell these situations apart.
